### ISSUE TITLE
Compile error php5.6.40

### ISSUE THREAD

**Issue by predators46** [m6w6/ext-raphf#10]
```
raphf-2.0.1/src/php_raphf_api.h:204:2: error: unknown type name 'zend_string'
```

**Comment by remicollet** [comment]
For PHP 5 you need raphf version 1  (last is 1.1.2)

Version 2.x is for PHP 7/8

P.S. also see https://www.php.net/supported-versions.php

**Comment by predators46** [comment]
Thanks
